- hosts: all
  tasks:
    - name: wait until ec2 instance is ready
      include_role:
        name: wait_ec2
      tags: wait_ec2

    - name: install packages
      include_role:
        name: init
      tags: pkg

    - name: start minecraft server
      include_role:
        name: minecraft
      tags: minecraft

    - name: setup backup
      include_role:
        name: backup
      tags: backup
