- hosts: all
  vars_files:
    - playbook_vars.yaml

  tasks:
    - name: wait until ec2 instance is ready
      include_role:
        name: wait_ec2
      tags: wait_ec2

    - name: install packages
      include_role:
        name: init
      tags: pkg

    - name: start minecraft server
      include_role:
        name: minecraft
      tags: minecraft

    - name: setup reboot
      cron:
        name: "start minecraft server on reboot"
        special_time: reboot
        job: "MAX_MEM={{ max_memory }} start.sh"

    - name: setup backup
      block:
        - name: create full backup folder
          file:
            path: ~/backup/full
            state: directory
            mode: 0755

        - name: create incremental backup folder
          file:
            path: ~/backup/incremental
            state: directory
            mode: 0755

        - name: copy backup script
          copy:
            src: backup.sh
            dest: backup.sh
            mode: 0755

        - name: set backup cron job
          cron:
            name: "backup world every 4hr"
            minute: "0"
            hour: "*/4"
            job: "backup.sh"
      tags: backup
