- name: install aws cli
  include_role:
    name: aws_cli
  tags: aws_cli

- name: copy backup script
  template:
    src: backup.sh.j2
    dest: "{{ minecraft_path }}/backup.sh"
    mode: 0755

- name: set backup cron job
  cron:
    name: "backup world every 4hr"
    minute: "0"
    hour: "*/4"
    job: "{{ minecraft_path }}/backup.sh"
